### ISSUE TITLE
Removing beta and updates checklist

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#57]
As we finalize new features and improvements, let's remove the `beta.` tag. 🎉 

### Minimum backlog

- [x] set up `map.` subdomain on Cloudflare
- [x] Handle redirects of old links with Cloudflare: `beta.openaerialmap.org/xyz` --> `map.openaerialmap.org/xyz`

### New features, Browser & Catalog updates

- [x] deploy dynamic tiler
  - [x] transcode and set up new HOT OIN bucket
  - [x] set up `tiles.` subdomains
  - [ ] complete full backlog here: https://github.com/hotosm/OpenAerialMap/issues/60
- [x]  grid and fill color over satellite imagery https://github.com/hotosm/oam-browser/issues/181
- [ ] <strike>Double click should always zoom https://github.com/hotosm/oam-browser/issues/185</strike> punt
- [x] integrate WMTS urls to browser https://github.com/hotosm/oam-browser/issues/189
- [x] Pan map across date line https://github.com/hotosm/oam-browser/issues/180
- [x] node version update https://github.com/hotosm/oam-catalog/issues/88

### Nice to haves but need help

- <strike>[ ] URL improvements: https://github.com/hotosm/oam-browser/issues/165. From this ticket, the two main items on the backlog would be:</strike>
  - <strike>to make the necessary changes within the browser for the new routes</strike>
  - <strike>implement server with nginx to handle the routing</strike>

**Comment by danielfdsilva** [comment]
@smit1678 since all oam tools are under subdomains, can we do the same for the browser? Like `map.openaerialmap.org`. That way we don't need to have subfolders and looks consistent.

**Comment by smit1678** [comment]
@danielfdsilva Well I guess that's a question we should be asking as well. Should the Uploader be at `upload.openaerialmap.org`? I think it's fine and makes sense to have the APIs on subdomains, but for longer term thinking and usability, do we want to move towards a more cohesive set of tools under the openaerialmap.org domain?

**Comment by danielfdsilva** [comment]
@smit1678 Actually I think the exact opposite. I think it's more usable to have subdomains rather than folders. Having folders also means you need to host everything on the same server.
The domain will always be `openaerialmap.org`, and the subdomain defines the tool.

**Comment by smit1678** [comment]
Discussed this some more and let's go with `map.openaerialmap.org` instead of `/map` for now. I think there will be reason to switch this as there becomes a need to integrate the pieces more as we look to have better account and user management, but this can be handled in a number of ways in the future. 

I edited the above list to be a minimum backlog for removing beta plus the nice to haves that are tagged as help wanted. Also adding a list of things to hit to start to include dynamic TMS integration which should be ready at the same time. 

@mojodna Can you edit the backlog above to drop in what else is needed for go live? I know some of this is being tracked in https://github.com/hotosm/oam-uploader-api/issues/52.

**Comment by ianschuler** [comment]
@danielfdsilva getting and SSL flag on the front page of the non-beta site

![ssl](https://cloud.githubusercontent.com/assets/1480842/22665928/b54bdb2e-ec84-11e6-8afd-9f81b8c1b8c2.png)

**Comment by danielfdsilva** [comment]
I traced the problem to the "Latest Images". These come from the oam-catalog api and the returned link in not in https format.
This should be changed in the source, but in the meantime a possible solution would be replacing `http` with `https` before printing it.

cc @ianschuler @smit1678

**Comment by smit1678** [comment]
@danielfdsilva Thanks for looking into this. It will be easier to change the HOT controlled metadata at the source, but in places like Astro Digital, I don't think we'll be able to fully control whether thumbnail endpoints are http or https since this metadata is generated by them. What would you suggest we do to handle non-https links?

**Comment by danielfdsilva** [comment]
I don't think there's much we can do. You can't force https if you are not sure if the resources are https

**Comment by smit1678** [comment]
Closing this thread and opened a new one to track thumbnail mixed content in #76
