### ISSUE TITLE
Dynamic Tiling launch checklist

### ISSUE THREAD

**Issue by mojodna** [hotosm/OpenAerialMap#60]
## PRs to land:

- [x] (`oam-catalog`) [Dynamic tiling-related indexing improvements](https://github.com/hotosm/oam-catalog/pull/85)
- [x] (`oin-register`) [Replacement HOT Bucket](https://github.com/openimagerynetwork/oin-register/pull/16)
- [x] (`oam-uploader-api`) [TMS-ready processing](https://github.com/hotosm/oam-uploader-api/pull/66)
- [x] (`oam-catalog`) [deploy to production](https://github.com/hotosm/oam-catalog/pull/89)

## After re-deploying `oam-catalog`

- [x] re-index HOT OIN bucket (`s3://oin-hotosm`)
- [x] remove metadata referencing old HOT OIN bucket (`s3://hotosm-oam`)

## Before re-deploying `oam-uploader-api`

- [x] ~Create Batch job definition for the Uploader~
- [x] ~Create Batch job queue for the Uploader~

## When re-redeploying `oam-uploader-api`

- [x] reconfigure to use `s3://oin-hotosm` (`OIN_BUCKET`, possibly `AWS_REGION` (`us-east-1`))
- [x] ~reconfigure to use Batch (`USE_BATCH=true`, `JOB_DEFINITION=arn:aws:batch:us-east-1:█████:job-definition/...:4`, `JOB_QUEUE=arn:aws:batch:us-east-1:█████:job-queue/...`~
- [x] ~reconfigure to automatically add a TMS (`DYNAMIC_TMS=true`, `TMS_PREFIX=http://tiles.openaerialmap.org/`)~

## General Tasks

- [x] push `oam-dynamic-tiler-tools` Docker image (processing variant) to `quay.io/hotosm/oam-processor`
- [x] ~push `oam-dynamic-tiler` Docker image (Batch variant) to `quay.io/hotosm/oam-processor-batch` (needed for the Batch job definition)~
- [x] notify other users of `oam-catalog` that HOT's new OIN bucket will break existing code (who are those users?)
- [x] contact AWS support about Lambda limit increases

@smit1678 @cgiovando: what am I missing?

**Comment by smit1678** [comment]
👍  

For OIN replacement bucket, https://github.com/openimagerynetwork/oin-register/pull/16, we may want to give heads up that older version of the catalog break. @mojodna @cgiovando Do we know how many other catalogs are being actively run and used? 

> remove metadata referencing old HOT OIN bucket (s3://hotosm-oam)

Tested this on staging and can quickly drop the `meta` collection and it will be recreated upon new index.

**Comment by mojodna** [comment]
> Do we know how many other catalogs are being actively run and used?

I'm only aware of the one.

> Tested this on staging and can quickly drop the meta collection and it will be recreated upon new index.

Astro Digital IDs will also be re-created, but that's probably fine too.

**Comment by smit1678** [comment]
@mojodna Sent an update to the OAM mailing list as well as on Gitter. 👍
